<?php include('includes/header.php'); ?>

<main class="container mt-4">
  <h1>Gerador de Currículo</h1>

  <form action="gerar.php" method="POST">
    <label>Nome:</label>
    <input type="text" name="nome" required>s

    <label>Email:</label>
    <input type="email" name="email" required>

    <label>Telefone:</label>
    <input type="text" name="telefone">

    <label>Data de nascimento:</label>
    <input type="date" name="nascimento">

    <label>Sobre você:</label>
    <textarea name="sobre"></textarea>

    <button type="submit">Gerar Currículo</button>
  </form>
</main>

<?php include('includes/footer.php'); ?>
